import {useEffect}from 'react';
import {createRoot} from 'react-dom/client';

import '../src/assets/style.css';

function calculateRowsColumns(totalCards) {
  // Calculate the square root
  let squareRoot = Math.sqrt(totalCards);
  
  // Determine the number of rows and columns
  let rows = Math.floor(squareRoot);
  let columns = Math.ceil(totalCards / rows);

  return { rows, columns };
}


async function addStickyNotes(ideas) {
  const { rows, columns } = calculateRowsColumns(ideas.length);
  // Calculate the size of the frame
  // let width = columns * 200;
  // let height = rows * 200;
  // const frame = await miro.board.createFrame({
  //   title: 'Ideas Generated by Moro-Miro',
  //   style: {
  //     fillColor: '#ffffff',
  //   },
  //   x: 0, 
  //   y: 0, 
  //   width: 800,
  //   height: 450,
  // });
  let curr_row = -1;
  let curr_col = 0;
  for (let i = 0; i < ideas.length; i++) {
    if (i % columns === 0) {
      curr_row++;
      curr_col = 0;
    }
    const stickyNote = await miro.board.createStickyNote({
      content: ideas[i],
      relativeTo: "parent_top_left",
      x: 0 + curr_col * 200,
      y: 0 + curr_row * 200,
    });
    // frame.add(stickyNote);
    curr_col++;
  }

}

async function addCards(cards){
  for (let i = 0; i < cards.length; i++) {
    const card = await miro.board.createCard(cards[i]);
    await miro.board.viewport.zoomTo(card);
  }

}

const App = () => {
    let ideas = ["test1", "test2", "test3","test1", "test2", "test3","test1", "test2", "test3","test2", "test3"]
    let cards = [{title:"test", description: 'hello world', dueDate: '2021-08-29'}, {title:"test2", description: 'hello world2'}, {title:"test3", description: 'hello world3', dueDate: '2021-08-29'}]

  return (
    <div>
      <h1>Moro-Miro</h1>
      <p>Click the button to add sticky notes</p>
      <button className="btn btn-primary" onClick={()=>addStickyNotes(ideas)}>
        Add sticky notes
      </button>
      <button className="btn btn-primary" onClick={()=>addCards(cards)}>
        Add cards
      </button>
    </div>
  );
};

const container = document.getElementById('root');
const root = createRoot(container);
root.render(<App />);
